### ISSUE TITLE
Unable to parse GCal events

### ISSUE THREAD

**Issue by bbkgh** [sawhney17/logseq-calendars-plugin#48]
Hi. Google Calendar events cannot be parsed in version 0.9.10.

```
index.16481dfd.js:3 Uncaught (in promise) Error: true is not ISeqable
    at $APP.$cljs$core$seq$$ (core.cljs:1255:7)
    at $cljs$core$seq_reduce$cljs$0core$0IFn$0_invoke$0arity$03$$ (core.cljs:2500:28)
    at $APP.$cljs$core$reduce$$.$cljs$core$IFn$_invoke$arity$3$ (core.cljs:2538:1)
    at $cljs$core$transduce$$.$cljs$core$IFn$_invoke$arity$4$ (core.cljs:2614:1)
    at $APP.$cljs$core$into$$.$cljs$core$IFn$_invoke$arity$3$ (core.cljs:5274:30)
    at $logseq$graph_parser$text$extract_refs_from_mldoc_ast$$ (text.cljs:132:8)
    at core.cljs:4762:5
    at core.cljs:4762:5
    at $JSCompiler_StaticMethods_sval$$ (core.cljs:3452:10)
    at $APP.$JSCompiler_prototypeAlias$$.$cljs$core$ISeqable$_seq$arity$1$ (core.cljs:3520:5)
    at $APP.$cljs$core$seq$$ (core.cljs:1238:15)
    at $cljs$core$bounded_count$$ (core.cljs:3799:21)
    at $APP.$cljs$core$apply$$.$cljs$core$IFn$_invoke$arity$2$ (core.cljs:3965:29)
    at $APP.$cljs$core$mapcat$$.$cljs$core$IFn$_invoke$arity$variadic$ (core.cljs:5188:1)
    at $logseq$graph_parser$block$get_page_ref_names_from_properties$$ (block.cljs:165:28)
    at $logseq$graph_parser$block$get_page_refs_from_properties$$ (block.cljs:423:21)
    at $frontend$handler$page$build_page_tx$$ (editor.cljs:643:3)
    at $frontend$handler$page$create_BANG_$cljs$0core$0IFn$0_invoke$0arity$02$$ (page.cljs:166:21)
    at Kr.<anonymous> (api.cljs:545:21)
    at Kr.Lt (lsplugin.core.js:2:58291)
    at Kr.<anonymous> (lsplugin.core.js:2:94523)
    at a.emit (lsplugin.core.js:2:26980)
    at Vt.<anonymous> (lsplugin.core.js:2:89915)
    at lsplugin.core.js:2:62297
    at Array.forEach (<anonymous>)
    at Vt.listener (lsplugin.core.js:2:62282)

```

**Comment by reinaldoluckman** [comment]
[See this thread](https://github.com/sawhney17/logseq-calendars-plugin/issues/9).  Probably a date format issue.
